Enable drag and drop for step listview
ABI-Software/mapclientplugins.geometryfitter pull request #19
Opened 2021-06-01 03:37 UTC by Kayvv

2022-08-24 03:24 UTC, hsorby requested changes

2022-08-24 03:24 UTC, hsorby commented on mapclientplugins/geometryfitter/view/geometryfitterwidget.py
> +        self._ui.displayMaxError_lineEdit.setText("TEST22!")
These "values" will come from the model in the future `self._model.rmsError()` and `self._model.maxError()`. Might as well have these in place now.

2022-08-24 03:24 UTC, hsorby commented on mapclientplugins/geometryfitter/view/geometryfitterwidget.py
> +            fitterSteps = self._fitter.getFitterSteps()
Why bother getting fitter steps if you are not going to use them.

2022-08-25 04:46 UTC, hsorby commented
@rchristie has implemented the fitting error calculation in scaffoldfitter now (and it has been merged in), that means this PR can be finished off @Kayvv.

2022-08-25 08:23 UTC, Kayvv commented
> @rchristie has implemented the fitting error calculation in scaffoldfitter now (and it has been merged in), that means this PR can be finished off @Kayvv.

I will start a new PR for display_error. This is an old PR for drag_drop, sorry I merged display_error here just for update and testing.

2022-08-25 08:25 UTC, hsorby commented
> I will start a new PR for display_error. This is an old PR for drag_drop, sorry I merged display_error here just for update and testing.

Are you going to remove the display_error parts that don't belong in this PR?

2022-08-25 09:28 UTC, Kayvv commented
Yep, I’ll merge the main branch in again once display_error has been merged into main and fix the conflicts. I found another bug here today (the display group doesn’t work after reordering the step list) so probably needs more testing and debugging. I this this PR has less priority than display_error.

Sent from my iPhone

> On 25/08/2022, at 20:25, Hugh Sorby ***@***.***> wrote:
> 
> ﻿
> I will start a new PR for display_error. This is an old PR for drag_drop, sorry I merged display_error here just for update and testing.
> 
> Are you going to remove the display_error parts that don't belong in this PR?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.

2022-08-26 02:37 UTC, hsorby approved these changes
Looks great and works well, thanks.

2022-08-26 02:37 UTC, merged